version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  iot-config:
    container_name: iot-config
    image: iotplatform/iot-config:v2
    expose:
      - 7001
    ports:
      - "7001:7001"


  iot-config-test:
    container_name: iot-config-test
    image: iotplatform/iot-config-test:v2
    ports:
      - "7002:7002"
    links:
      - iot-config:iot-config
    depends_on:
      - iot-config
